#version: "3.3"

services:
  normal_map_generator:
    # you can change this to whatever you want.
    container_name: normal_map_generator
    build:
      context: ./
      dockerfile: ./Dockerfile
      shm_size: '100gb'
    shm_size: '100gb'
    volumes:
      - "./:/NormalMapGenerator"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
